<?php

namespace Ordr\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrdrMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdrMetaRepository extends EntityRepository
{
  public function findByPublic()
  {
    $em = $this->getEntityManager();

    $metas = $em
      ->createQuery('SELECT o FROM OrdrDataBundle:OrdrMeta o WHERE o.public = :public AND o.created_at > :start')
      ->setParameter("public", true)
      ->setParameter("start", new \DateTime('1970-01-01'))
      ->getResult();

    return $metas;
  }
}